### ISSUE TITLE
Massive Spamming Handling

### ISSUE THREAD

**Issue by alph0x** [kohtenko/KODropdownNotification#1]
Hi, i'm doing some tests with KODropdownNotification and when I create a lot of notifications, the constraints start to collapse and finally crash at the end.

<------
2015-08-17 10:13:47.527 blancride[460:25850] Unable to simultaneously satisfy constraints.
    Probably at least one of the constraints in the following list is one you don't want. Try this: (1) look at each constraint and try to figure out which you don't expect; (2) find the code that added the unwanted constraint or constraints and fix it. (Note: If you're seeing NSAutoresizingMaskLayoutConstraints that you don't understand, refer to the documentation for the UIView property translatesAutoresizingMaskIntoConstraints) 
(
    "<NSLayoutConstraint:0x16850e10 V:|-(-66)-[Notification:0x17c0c880]   (Names: '|':UIWindow:0x157a7ed0 )>",
    "<NSLayoutConstraint:0x1983ce50 V:|-(0)-[Notification:0x17c0c880]   (Names: '|':UIWindow:0x157a7ed0 )>"
)

Will attempt to recover by breaking constraint 
<NSLayoutConstraint:0x1983ce50 V:|-(0)-[Notification:0x17c0c880]   (Names: '|':UIWindow:0x157a7ed0 )>

Make a symbolic breakpoint at UIViewAlertForUnsatisfiableConstraints to catch this in the debugger.
The methods in the UIConstraintBasedLayoutDebugging category on UIView listed in <UIKit/UIView.h> may also be helpful.
------>

**Comment by kohtenko** [comment]
Can you provide code for creating such error? I've never seen constraints error in `KODropdownNotification` before

**Comment by alph0x** [comment]
I've just created a Notification Class with:
Notification.h
#import "KODropdownNotification.h"

@interface Notification : KODropdownNotification
@property (strong, nonatomic) IBOutlet UIImageView *notificationPicture;
@property (strong, nonatomic) IBOutlet UILabel *notificationMessage;

+(instancetype) initNotification;
-(void) presentNotification:(Notification *) notification;

@end

Notification.m

@implementation Notification {

}

+(instancetype) initNotification {
    return [[Notification alloc] initWithNibName:@"Notification"];
}

-(void) presentNotification:(Notification *) notification {

```
MenuViewController *sideMenu = [AppDelegate shareDelegate].sideMenu;
UIViewController *showedController= sideMenu.slidingViewController.mainViewController;
UINavigationController *navigationController=(UINavigationController *)showedController;
navigationController.navigationBar.fixedHeightWhenStatusBarHidden = YES;
notification.dismissOnSwipe = YES;
notification.dismissOnTap = YES;

[notification showAnimated:YES];
[[UIApplication sharedApplication] setStatusBarHidden:YES withAnimation:UIStatusBarAnimationNone];
dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(5 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
    [notification dismissAnimated:YES];



});
```

}

@end

///////

And the presentation is a simple method

-(void) showInAppNotification: (NSString *) message
{

```
self.notification.delegate = self;
self.notification.notificationPicture.image = self.roomForNotification.userPicture;
self.notification.notificationMessage.text = message;
[self.notification presentNotification:self.notification];
```

}

(This is a NSObject Class, the self.notification init is on -init)

In the presentNotification method i use a helper to hide the status bar, because i try to use the property you have on KODropDownNotification but it wasn't hiding the status bar.

**Comment by kohtenko** [comment]
Unfortunately, hiding of status bar is not so trivial and can't be organised "inside of box". In 1.1.2 release, there is `NSNotification` named `updateStatusBar`. You can add observer to `NSNotificationCenter.defaultCenter()` in any place in your code and do any changes with your status bar.

About your issue, I can't give you any clue, cause I don't have enough information, I even can't reproduce it in my demo project.

**Comment by alph0x** [comment]
Well, thanks anyway, i'll try to figure it out, if i find anything i'll let you know for information purposes.
